# Generated by Django 5.2 on 2025-04-11 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_instalacion', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_mantenimiento', models.DateField()),
                ('historial_mantenimiento', models.TextField(blank=True, null=True)),
                ('ph', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)])),
                ('temperatura', models.FloatField(help_text='Temperatura en °C')),
                ('conductividad', models.FloatField(help_text='Conductividad eléctrica en µS/cm')),
                ('turbidez', models.FloatField(help_text='Turbidez en NTU')),
                ('nivel_del_agua', models.FloatField(help_text='Nivel del agua en cm o %')),
                ('historial_datos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dispositivos',
            },
        ),
        migrations.CreateModel(
            name='TanqueAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.FloatField(help_text='Capacidad en litros')),
                ('color', models.CharField(choices=[('azul', 'Azul'), ('blanco', 'Blanco'), ('negro', 'Negro')], max_length=50)),
                ('fecha_instalacion', models.DateField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_mantenimiento', models.DateField()),
                ('historial_mantenimiento', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to='App.dispositivo')),
            ],
            options={
                'db_table': 'tanques_agua',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('tanque_agua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='App.tanqueagua')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
